### ISSUE TITLE
No module named 'telegram'

### ISSUE THREAD

**Issue by JustAKat** [dracarys18/TweetBot#12]
After performing all the steps up to the requirements installing, when attempting to execute the bot, this error occurs:

    root:~/TweetBot# python3.6 TweetBot/main.py
    Traceback (most recent call last):
      File "TweetBot/main.py", line 1, in <module>
        import telegram
    ModuleNotFoundError: No module named 'telegram'

This is the produced log whilst installing the requirements:
https://www.toptal.com/developers/hastebin/ikaqisetok.apache

Wish to seek your advice in resolving the issue

**Comment by JustAKat** [comment]
Update:

In case if needed, here are the slightly modified steps used, whilst trying to resolve that issue:

    cd TweetBot
    python3 -m venv telegramtwitterenv
    
    . telegramtwitterenv/bin/activate
    
    pip install -r requirements.txt
    pip install telegram

    python3.6 main.py

**Comment by dracarys18** [comment]
Looks like your pip is using an older version of python you have check it by running
`ls -l `which pip`` to confirm. You can just run `python3.6 -m pip install -r requirements.txt` and run main.py again.

**Comment by JustAKat** [comment]
That resolved that error, thanks!

Unfortunately, there's another snag now

Retrieved the channel ID via @getidsbot, and neither of the variations below seem to be working:

    export CHAT_ID="-1001720436594"

    export CHAT_ID=-1001720436594

    export CHAT_ID="1720436594"

An attempt has also been made to use the human readable form of the public channel's link to no avail.

Error displayed is:

    Traceback (most recent call last):
      File "TweetBot/main.py", line 6, in <module>
        import tweet_scrape as ts
      File "/root/Telegram_TweetBot/TweetBot/tweet_scrape.py", line 13, in <module>
        chatid = int(os.getenv("CHAT_ID"))
    TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
