### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by amitwadhianivia** [dracarys18/TweetBot#16]
Hi,
I am very new to python.
Environment variables in keys is a bit unclear for me as I am getting error that access token is invalid for telegram but I tried various combinations of putting either access token of telegram bot or Twitter API, but nothing is working for me.
Can you please add a few comments on the env file for how to configure that?
That would be a great help..
I know this could be a stupid question as many people are using this successfully.
Thanks in advance
Amit

**Comment by dracarys18** [comment]
Please check README.md I have made it clear what to fill in the .env file

**Comment by cryptedbv** [comment]
it is indeed pretty unclear and could be answered. I've added quite a few bots with different guides, but the terminology here does not make much sense. As in the Twitter API creation page it is called "API Key" and "API Key Secret". It would make much more sense to everyone to just use the exact words that are mentioned there. Plus with Telegram you get one long string. So it indeed does not make sense. So I totally get what @amitwadhianivia is saying.

**Comment by dracarys18** [comment]
> it is indeed pretty unclear and could be answered. I've added quite a few bots with different guides, but the terminology here does not make much sense. As in the Twitter API creation page it is called "API Key" and "API Key Secret". It would make much more sense to everyone to just use the exact words that are mentioned there. Plus with Telegram you get one long string. So it indeed does not make sense. So I totally get what @amitwadhianivia is saying.
> 
> So the first 2 are the API Key and API Secret, the TELEGRAM_BOT is the string you got in telegram when creating it the last 2 are from Twitter again when generating it. (under keys it says Access tokens and Secret)
> 
> Lastly, chat ID, you can find that using a bot or web.telegram.org.

Thanks for your input, will try to make it as clear as possible.

**Comment by dracarys18** [comment]
@cryptedbv If you have setup the bot can you make a PR to improve the README where it can be improved?

**Comment by cryptedbv** [comment]
> @cryptedbv If you have setup the bot can you make a PR to improve the README where it can be improved?

Unable to to now, but you could do it in the keys file.

`# Please rename this file to keys.env after filling these
#
# CONSUMER_KEY = API Key TWITTER
# CONSUMER_SECRET = API Key Secret TWITTER
# TELEGRAM_BOT = TOKEN that you got from BotFather in TELEGRAM
# ACCESS_TOKEN = Access Token in TWITTER
# ACCESS_TOKEN_SECRET = Access Token Secret in TWITTER
# CHAT_ID = Add '@username_to_id_bot' to your Group or Channel, say something and it will show your channel/group ID, include the '-' infront of the numbers.

export CONSUMER_KEY=""
export CONSUMER_SECRET=""
export TELEGRAM_BOT=""
export ACCESS_TOKEN=""
export ACCESS_TOKEN_SECRET=""
export CHAT_ID=`

**Comment by GabriellCosta** [comment]
> > @cryptedbv If you have setup the bot can you make a PR to improve the README where it can be improved?
> 
> Unable to to now, but you could do it in the keys file.
> 
> ```
> # Please rename this file to keys.env after filling these
> #
> # CONSUMER_KEY = API Key TWITTER
> # CONSUMER_SECRET = API Key Secret TWITTER
> # TELEGRAM_BOT = TOKEN that you got from BotFather in TELEGRAM
> # ACCESS_TOKEN = Access Token in TWITTER
> # ACCESS_TOKEN_SECRET = Access Token Secret in TWITTER
> # CHAT_ID = Add '@username_to_id_bot' to your Group or Channel, say something and it will show your channel/group ID, include the '-' infront of the numbers.
> 
> export CONSUMER_KEY=""
> export CONSUMER_SECRET=""
> export TELEGRAM_BOT=""
> export ACCESS_TOKEN=""
> export ACCESS_TOKEN_SECRET=""
> export CHAT_ID=
> ```

I opened a PR about that https://github.com/dracarys18/TweetBot/pull/20

**Comment by dracarys18** [comment]
> > > @cryptedbv If you have setup the bot can you make a PR to improve the README where it can be improved?
> > 
> > 
> > Unable to to now, but you could do it in the keys file.
> > ```
> > # Please rename this file to keys.env after filling these
> > #
> > # CONSUMER_KEY = API Key TWITTER
> > # CONSUMER_SECRET = API Key Secret TWITTER
> > # TELEGRAM_BOT = TOKEN that you got from BotFather in TELEGRAM
> > # ACCESS_TOKEN = Access Token in TWITTER
> > # ACCESS_TOKEN_SECRET = Access Token Secret in TWITTER
> > # CHAT_ID = Add '@username_to_id_bot' to your Group or Channel, say something and it will show your channel/group ID, include the '-' infront of the numbers.
> > 
> > export CONSUMER_KEY=""
> > export CONSUMER_SECRET=""
> > export TELEGRAM_BOT=""
> > export ACCESS_TOKEN=""
> > export ACCESS_TOKEN_SECRET=""
> > export CHAT_ID=
> > ```
> 
> I opened a PR about that #20

Cool thanks

**Comment by dracarys18** [comment]
Closing this issue now that we have a pretty clear README and a sample env file.
