### ISSUE TITLE
can't run TweetBot

### ISSUE THREAD

**Issue by siko0r** [dracarys18/TweetBot#24]
Hi. 

After command :   cargo run --release I geting this error. 
All fields in .env file I have correct. 

maybe is miss something ?  

sikor@sikor-ubu:~/TweetBot$ cargo run --release
warning: function is never used: `get_url_entity`
  --> src/utils.rs:25:14
   |
25 | pub async fn get_url_entity(tweet: &Tweet) -> Option<String> {
   |              ^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: function is never used: `get_media_urls`
  --> src/utils.rs:36:14
   |
36 | pub async fn get_media_urls(tweet: &Tweet) -> Option<Vec<String>> {
   |              ^^^^^^^^^^^^^^

warning: associated function is never used: `new`
  --> src/error/tweet_error.rs:22:12
   |
22 |     pub fn new(kind: TweetErrorKind) -> Self {
   |            ^^^

warning: `tweet_bot` (bin "tweet_bot") generated 3 warnings
    Finished release [optimized] target(s) in 0.08s
     Running `target/release/tweet_bot`
thread 'main' panicked at 'Cannot get the TELOXIDE_TOKEN env variable', /home/sikor/.cargo/registry/src/github.com-1ecc6299db9ec823/teloxide-core-0.5.1/src/bot.rs:298:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by dracarys18** [comment]
You need to set TELOXIDE_TOKEN env variable
