### ISSUE TITLE
Error: TweetError { kind: TweetError(BadStatus(403))

### ISSUE THREAD

**Issue by spin240** [dracarys18/TweetBot#26]
Hey, I have filled everything in .env file, however I can't run my TweetBot. Could you please tell me what could be the problem?

warning: function is never used: `get_url_entity`
  --> src/utils.rs:25:14
   |
25 | pub async fn get_url_entity(tweet: &Tweet) -> Option<String> {
   |              ^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: function is never used: `get_media_urls`
  --> src/utils.rs:36:14
   |
36 | pub async fn get_media_urls(tweet: &Tweet) -> Option<Vec<String>> {
   |              ^^^^^^^^^^^^^^

warning: associated function is never used: `new`
  --> src/error/tweet_error.rs:22:12
   |
22 |     pub fn new(kind: TweetErrorKind) -> Self {
   |            ^^^

warning: `tweet_bot` (bin "tweet_bot") generated 3 warnings
    Finished release [optimized] target(s) in 0.12s
     Running `target/release/tweet_bot`
Started the stream
Error: TweetError { kind: TweetError(BadStatus(403)), location: Location { file: "src/stream/stream_impl.rs", line: 15, col: 5 } }

**Comment by dracarys18** [comment]
Hey, I am really sorry for the late response I have been busy with work. Twitter API throws 403 error if it's not authorized properly. So please check if you have the relevant key required to run the bot.

**Comment by VatraXD** [comment]
>I have filled everything in .env file

>So please check if you have the relevant key required to run the bot.

At least you could have been more elaborate. I have the same issue and I filled everything out perfectly.

**Comment by psx369** [comment]
I'm getting the same issue, this seems broken.

**Comment by StarvingDeveloper** [comment]
Same problem for me. @dracarys18 where I susspose to enter bearer token? I seen without that token you cant authorize anymore.

**Comment by lockcmd** [comment]
> Same problem for me. @dracarys18 where I susspose to enter bearer token? I seen without that token you cant authorize anymore.

Have you solved this problem?
