### ISSUE TITLE
JavaScript version

### ISSUE THREAD

**Issue by Ibinola** [dracarys18/TweetBot#27]
Hey! I would love to rewrite this using javascript

**Comment by dracarys18** [comment]
![Uploading 20170424-4O1GHDF3vyAAcQfG8B1r.jpg…]()

**Comment by dracarys18** [comment]
![20170424-4O1GHDF3vyAAcQfG8B1r](https://user-images.githubusercontent.com/43412619/171409759-4734bbea-ed26-430c-9bc7-0b500317b525.jpg)
