### ISSUE TITLE
cannot get the teloxide token env variable

### ISSUE THREAD

**Issue by CryDev1l** [dracarys18/TweetBot#28]
Hello. Can you help me understand why this error occurs? I did everything according to the instructions

**Comment by dracarys18** [comment]
You need to export `TELOXIDE_TOKEN` as an environment variable with your bot token. I guess I forgot to change it in the sample env file. I will do that now

**Comment by dracarys18** [comment]
Done in https://github.com/dracarys18/TweetBot/commit/b764c4a6a0e114861168fcfde41f20beefe4a537
