### ISSUE TITLE
Forbidden: bot can't send messages to the user

### ISSUE THREAD

**Issue by cyb3rx7n** [dracarys18/TweetBot#6]
Forbidden: bot can't send messages to the user

**Comment by dracarys18** [comment]
> yes i did start to bot but still not working btw i need to connect bot to channel

Make the bot admin and  set

**Comment by dracarys18** [comment]
> it's work with group but with channel no chance ?

It works with both channel and group

**Comment by dracarys18** [comment]
> no just with group i get it work what the mothed that you get id of channel ?

You don't even know your channel id and you are claiming it doesn't work with channel I am closing the issue

Regarding getting the channel id just forward any message from your channel to @JsonDumpBot on telegram
